### ISSUE TITLE
More detailed usage instructions

### ISSUE THREAD

**Issue by NikosAlexandris** [anapsix/docker-alpine-java#83] opened 2019-04-18 14:28 UTC
Hi there,

would you care to add more detailed usage instructions/examples?  How do I go about in building a JRE docker image?  Is the following I am trying to do correct?

Create a "SE JRE" `Dockerfile`
```
./generate_dockerfiles.sh server-jre
```
and this, indeed, creates (a) new Dockerfile(s). Trying to use the file
```
docker-alpine-java/8/202b08/server-jre/standard/Dockerfile
```
to build an image via
```
docker build -f Dockerfile .
```

The build process, obviously as seen below, fails.
```
Sending build context to Docker daemon  6.144kB
Step 1/4 : FROM alpine:3.8
 ---> dac705114996
Step 2/4 : MAINTAINER Anastas Dancha <anapsix@random.io>
 ---> Using cache
 ---> a8f14c7a077c
Step 3/4 : ENV JAVA_VERSION_MAJOR=8     JAVA_VERSION_MINOR=202     JAVA_VERSION_BUILD=08     JAVA_PACKAGE=
server-jre     JAVA_JCE=standard     JAVA_HOME=/opt/jdk     PATH=${PATH}:/opt/jdk/bin     GLIBC_REPO=https
://github.com/sgerrand/alpine-pkg-glibc     GLIBC_VERSION=2.29-r0     LANG=C.UTF-8
 ---> Running in 7d6b138dc3bb
Removing intermediate container 7d6b138dc3bb
 ---> 9048436fe6d7
Step 4/4 : RUN set -ex &&     [[ ${JAVA_VERSION_MAJOR} != 7 ]] || ( echo >&2 'Oracle no longer publishes J
AVA7 packages' && exit 1 ) &&     apk -U upgrade &&     apk add libstdc++ curl ca-certificates bash java-c
acerts &&     wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
&&     for pkg in glibc-${GLIBC_VERSION} glibc-bin-${GLIBC_VERSION} glibc-i18n-${GLIBC_VERSION}; do curl -
sSL ${GLIBC_REPO}/releases/download/${GLIBC_VERSION}/${pkg}.apk -o /tmp/${pkg}.apk; done &&     apk add /t
mp/*.apk &&     rm -v /tmp/*.apk &&     ( /usr/glibc-compat/bin/localedef --force --inputfile POSIX --char
map UTF-8 C.UTF-8 || true ) &&     echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh &&     /usr/glibc
-compat/sbin/ldconfig /lib /usr/glibc-compat/lib &&     mkdir /opt &&     curl -jksSLH "Cookie: oraclelice
nse=accept-securebackup-cookie" -o /tmp/java.tar.gz       http://download.oracle.com/otn-pub/java/jdk/${JA
VA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/1961070e4c9b4e26a04e7f5a083f551e/${JAVA_PAC
KAGE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz &&     JAVA_PACKAGE_SHA256=$(curl -sSL
https://www.oracle.com/webfolder/s/digest/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}checksum.html | grep
-E "${JAVA_PACKAGE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64\.tar\.gz" | grep -Eo '(sha256: )
[^<]+' | cut -d: -f2 | xargs) &&     echo "${JAVA_PACKAGE_SHA256}  /tmp/java.tar.gz" > /tmp/java.tar.gz.sh
a256 &&     sha256sum -c /tmp/java.tar.gz.sha256 &&     gunzip /tmp/java.tar.gz &&     tar -C /opt -xf /tm
p/java.tar &&     ln -s /opt/jdk1.${JAVA_VERSION_MAJOR}.0_${JAVA_VERSION_MINOR} /opt/jdk &&     find /opt/
jdk/ -maxdepth 1 -mindepth 1 | grep -v jre | xargs rm -rf &&     cd /opt/jdk/ && ln -s ./jre/bin ./bin &&
    if [ "${JAVA_JCE}" == "unlimited" ]; then echo "Installing Unlimited JCE policy" &&       curl -jksSLH
 "Cookie: oraclelicense=accept-securebackup-cookie" -o /tmp/jce_policy-${JAVA_VERSION_MAJOR}.zip         h
ttp://download.oracle.com/otn-pub/java/jce/${JAVA_VERSION_MAJOR}/jce_policy-${JAVA_VERSION_MAJOR}.zip &&
     cd /tmp && unzip /tmp/jce_policy-${JAVA_VERSION_MAJOR}.zip &&       cp -v /tmp/UnlimitedJCEPolicyJDK8
/*.jar /opt/jdk/jre/lib/security/;     fi &&     sed -i s/#networkaddress.cache.ttl=-1/networkaddress.cach
e.ttl=10/ $JAVA_HOME/jre/lib/security/java.security &&     apk del curl glibc-i18n &&     rm -rf /opt/jdk/
jre/plugin            /opt/jdk/jre/bin/javaws            /opt/jdk/jre/bin/jjs            /opt/jdk/jre/bin/
orbd            /opt/jdk/jre/bin/pack200            /opt/jdk/jre/bin/policytool            /opt/jdk/jre/bi
n/rmid            /opt/jdk/jre/bin/rmiregistry            /opt/jdk/jre/bin/servertool            /opt/jdk/
jre/bin/tnameserv            /opt/jdk/jre/bin/unpack200            /opt/jdk/jre/lib/javaws.jar
/opt/jdk/jre/lib/deploy*            /opt/jdk/jre/lib/desktop            /opt/jdk/jre/lib/*javafx*
   /opt/jdk/jre/lib/*jfx*            /opt/jdk/jre/lib/amd64/libdecora_sse.so            /opt/jdk/jre/lib/a
md64/libprism_*.so            /opt/jdk/jre/lib/amd64/libfxplugins.so            /opt/jdk/jre/lib/amd64/lib
glass.so            /opt/jdk/jre/lib/amd64/libgstreamer-lite.so            /opt/jdk/jre/lib/amd64/libjavaf
x*.so            /opt/jdk/jre/lib/amd64/libjfx*.so            /opt/jdk/jre/lib/ext/jfxrt.jar            /o
pt/jdk/jre/lib/ext/nashorn.jar            /opt/jdk/jre/lib/oblique-fonts            /opt/jdk/jre/lib/plugi
n.jar            /tmp/* /var/cache/apk/* &&     ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/jre/lib/secu
rity/cacerts &&     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf
 ---> Running in 98cb3a09dbd4
+ '[[' 8 '!=' 7 ]]
+ apk -U upgrade
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
OK: 4 MiB in 13 packages
+ apk add libstdc++ curl ca-certificates bash java-cacerts
(1/17) Installing ncurses-terminfo-base (6.1_p20180818-r1)
(2/17) Installing ncurses-terminfo (6.1_p20180818-r1)
(3/17) Installing ncurses-libs (6.1_p20180818-r1)
(4/17) Installing readline (7.0.003-r0)
(5/17) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
(6/17) Installing ca-certificates (20171114-r3)
(7/17) Installing nghttp2-libs (1.32.0-r0)
(8/17) Installing libssh2 (1.8.2-r0)
(9/17) Installing libcurl (7.61.1-r2)
(10/17) Installing curl (7.61.1-r2)
(11/17) Installing libffi (3.2.1-r4)
(12/17) Installing p11-kit (0.23.10-r0)
(13/17) Installing libtasn1 (4.13-r0)
(14/17) Installing p11-kit-trust (0.23.10-r0)
(15/17) Installing java-cacerts (1.0-r0)
(16/17) Installing libgcc (6.4.0-r9)
(17/17) Installing libstdc++ (6.4.0-r9)
Executing busybox-1.28.4-r3.trigger
Executing ca-certificates-20171114-r3.trigger
OK: 18 MiB in 30 packages
+ wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
+ curl -sSL https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk -o /t
mp/glibc-2.29-r0.apk
+ curl -sSL https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-bin-2.29-r0.apk -
o /tmp/glibc-bin-2.29-r0.apk
+ curl -sSL https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-i18n-2.29-r0.apk
-o /tmp/glibc-i18n-2.29-r0.apk
+ apk add /tmp/glibc-2.29-r0.apk /tmp/glibc-bin-2.29-r0.apk /tmp/glibc-i18n-2.29-r0.apk
(1/3) Installing glibc (2.29-r0)
(2/3) Installing glibc-bin (2.29-r0)
(3/3) Installing glibc-i18n (2.29-r0)
Executing glibc-bin-2.29-r0.trigger
OK: 50 MiB in 33 packages
+ rm -v /tmp/glibc-2.29-r0.apk /tmp/glibc-bin-2.29-r0.apk /tmp/glibc-i18n-2.29-r0.apk
removed '/tmp/glibc-2.29-r0.apk'
removed '/tmp/glibc-bin-2.29-r0.apk'
removed '/tmp/glibc-i18n-2.29-r0.apk'
+ /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8
failed to set locale!
[warning] No definition for LC_PAPER category found
failed to set locale!
[warning] No definition for LC_NAME category found
failed to set locale!
[warning] No definition for LC_ADDRESS category found
failed to set locale!
[warning] No definition for LC_TELEPHONE category found
failed to set locale!
[warning] No definition for LC_MEASUREMENT category found
failed to set locale!
[warning] No definition for LC_IDENTIFICATION category found
+ true
+ echo 'export LANG=C.UTF-8'
+ /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib
+ mkdir /opt
+ curl -jksSLH 'Cookie: oraclelicense=accept-securebackup-cookie' -o /tmp/java.tar.gz http://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/server-jre-8u202-linux-x64.tar.gz
+ curl -sSL https://www.oracle.com/webfolder/s/digest/8u202checksum.html
+ grep -E 'server-jre-8u202-linux-x64\.tar\.gz'
+ grep -Eo '(sha256: )[^<]+'
+ cut -d: -f2
+ xargs
+ JAVA_PACKAGE_SHA256=61292e9d9ef84d9702f0e30f57b208e8fbd9a272d87cd530aece4f5213c98e4e
+ echo '61292e9d9ef84d9702f0e30f57b208e8fbd9a272d87cd530aece4f5213c98e4e  /tmp/java.tar.gz'
+ sha256sum -c /tmp/java.tar.gz.sha256
/tmp/java.tar.gz: FAILED
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
The command '/bin/sh -c set -ex &&     [[ ${JAVA_VERSION_MAJOR} != 7 ]] || ( echo >&2 'Oracle no longer publishes JAVA7 packages' && exit 1 ) &&     apk -U upgrade &&     apk add libstdc++ curl ca-certificates bash java-cacerts &&     wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub &&     for pkg in glibc-${GLIBC_VERSION} glibc-bin-${GLIBC_VERSION} glibc-i18n-${GLIBC_VERSION}; do curl -sSL ${GLIBC_REPO}/releases/download/${GLIBC_VERSION}/${pkg}.apk -o /tmp/${pkg}.apk; done &&     apk add /tmp/*.apk &&     rm -v /tmp/*.apk &&     ( /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true ) &&     echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh &&     /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib &&     mkdir /opt &&     curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /tmp/java.tar.gz       http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/1961070e4c9b4e26a04e7f5a083f551e/${JAVA_PACKAGE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz &&     JAVA_PACKAGE_SHA256=$(curl -sSL https://www.oracle.com/webfolder/s/digest/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}checksum.html | grep -E "${JAVA_PACKAGE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64\.tar\.gz" | grep -Eo '(sha256: )[^<]+' | cut -d: -f2 | xargs) &&     echo "${JAVA_PACKAGE_SHA256}  /tmp/java.tar.gz" > /tmp/java.tar.gz.sha256 &&     sha256sum -c /tmp/java.tar.gz.sha256 &&     gunzip /tmp/java.tar.gz &&     tar -C /opt -xf /tmp/java.tar &&     ln -s /opt/jdk1.${JAVA_VERSION_MAJOR}.0_${JAVA_VERSION_MINOR} /opt/jdk &&     find /opt/jdk/ -maxdepth 1 -mindepth 1 | grep -v jre | xargs rm -rf &&     cd /opt/jdk/ && ln -s ./jre/bin ./bin &&     if [ "${JAVA_JCE}" == "unlimited" ]; then echo "Installing Unlimited JCE policy" &&       curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /tmp/jce_policy-${JAVA_VERSION_MAJOR}.zip         http://download.oracle.com/otn-pub/java/jce/${JAVA_VERSION_MAJOR}/jce_policy-${JAVA_VERSION_MAJOR}.zip &&       cd /tmp && unzip /tmp/jce_policy-${JAVA_VERSION_MAJOR}.zip &&       cp -v /tmp/UnlimitedJCEPolicyJDK8/*.jar /opt/jdk/jre/lib/security/;     fi &&     sed -i s/#networkaddress.cache.ttl=-1/networkaddress.cache.ttl=10/ $JAVA_HOME/jre/lib/security/java.security &&     apk del curl glibc-i18n &&     rm -rf /opt/jdk/jre/plugin            /opt/jdk/jre/bin/javaws            /opt/jdk/jre/bin/jjs            /opt/jdk/jre/bin/orbd            /opt/jdk/jre/bin/pack200            /opt/jdk/jre/bin/policytool            /opt/jdk/jre/bin/rmid            /opt/jdk/jre/bin/rmiregistry            /opt/jdk/jre/bin/servertool            /opt/jdk/jre/bin/tnameserv            /opt/jdk/jre/bin/unpack200            /opt/jdk/jre/lib/javaws.jar            /opt/jdk/jre/lib/deploy*            /opt/jdk/jre/lib/desktop            /opt/jdk/jre/lib/*javafx*            /opt/jdk/jre/lib/*jfx*            /opt/jdk/jre/lib/amd64/libdecora_sse.so            /opt/jdk/jre/lib/amd64/libprism_*.so            /opt/jdk/jre/lib/amd64/libfxplugins.so            /opt/jdk/jre/lib/amd64/libglass.so            /opt/jdk/jre/lib/amd64/libgstreamer-lite.so            /opt/jdk/jre/lib/amd64/libjavafx*.so            /opt/jdk/jre/lib/amd64/libjfx*.so            /opt/jdk/jre/lib/ext/jfxrt.jar            /opt/jdk/jre/lib/ext/nashorn.jar            /opt/jdk/jre/lib/oblique-fonts            /opt/jdk/jre/lib/plugin.jar            /tmp/* /var/cache/apk/* &&     ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/jre/lib/security/cacerts &&     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf' returned a non-zero code: 1
```

**Comment by anapsix** [comment] 2019-04-18 15:27
during your build, last error message is `sha256sum: WARNING: 1 of 1 computed checksums did NOT match` - pointing out a SHA256 mismatch of downloaded `server-jre-8u202-linux-x64.tar.gz` and checksum listen on page https://www.oracle.com/webfolder/s/digest/8u202checksum.html

Unfortunately, looks like Oracle moved the downloads behind sing-in page.. So the regular curl trick with `-H 'Cookie: oraclelicense=accept-securebackup-cookie'` won't work any more.

You can use pre-built images from Docker Hub, and work on figuring out how to work around new Oracle's restrictions.

**Comment by anapsix** [comment] 2019-04-18 15:30
closing as duplicate of https://github.com/anapsix/docker-alpine-java/issues/82

**Closed as completed by anapsix** 2019-04-18 15:30 UTC
Labels: duplicate
